create table t_contact (
  id                            bigint generated by default as identity (start with 1)  not null,
  first_name                    varchar(50),
  last_name                     varchar(50),
  email                         varchar(200),
  phone                         varchar(20),
  customer_id                   bigint not null,
  constraint uq_t_contact_email unique (email),
  constraint pk_t_contact primary key (id)
);

create table t_customer (
  id                            bigint generated by default as identity (start with 1)  not null,
  name                          varchar(255),
  constraint pk_t_customer primary key (id)
);

create table t_sport (
  id                            bigint generated by default as identity (start with 1)  not null,
  name                          varchar(255),
  contact_id                    bigint not null,
  constraint pk_t_sport primary key (id)
);

alter table t_contact add constraint fk_t_contact_customer_id foreign key (customer_id) references t_customer (id) on delete restrict on update restrict;
create index ix_t_contact_customer_id on t_contact (customer_id);

alter table t_sport add constraint fk_t_sport_contact_id foreign key (contact_id) references t_contact (id) on delete restrict on update restrict;
create index ix_t_sport_contact_id on t_sport (contact_id);

