create table t_contact (
  id                            bigint generated by default as identity (start with 1)  not null,
  first_name                    varchar(50),
  last_name                     varchar(50),
  email                         varchar(200),
  phone                         varchar(20),
  customer_id                   bigint not null,
  constraint pk_t_contact primary key (id)
);

create table t_customer (
  id                            bigint generated by default as identity (start with 1)  not null,
  name                          varchar(255),
  constraint pk_t_customer primary key (id)
);

alter table t_contact add constraint fk_t_contact_customer_id foreign key (customer_id) references t_customer (id) on delete restrict on update restrict;
create index ix_t_contact_customer_id on t_contact (customer_id);

